
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: general
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
